[package]
name = "shinra"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "window"
path = "src/bin/window.rs"

[[bin]]
name = "terminal"
path = "src/bin/terminal.rs"

[dependencies]
wgpu = "22"
winit = "0.30"
pollster = "0.3"
bytemuck = { version = "1", features = ["derive"] }
glam = "0.28"
tobj = "4"
image = "0.25"
viuer = "0.7"
crossterm = "0.27"
anyhow = "1"
