// Vertex stage shared by every mesh pass in this game.
//
// `SeVertex` and `SeInstance` are generated by the host: the first from the
// mesh the pass named, the second from the component it named. Add a field to
// `Transform` in bundle/data.rs and it appears in `SeInstance` here, with no
// binding table to update.
// `Transform` in bundle/data.rs and it appears in `SeInstance` here, with no
// binding table to update.

struct VsOut {
    @builtin(position) clip   : vec4<f32>,
    @location(0)       normal : vec3<f32>,
    @location(1)       world  : vec3<f32>,
};

fn view_proj() -> mat4x4<f32> {
    let aspect = se.resolution.x / max(se.resolution.y, 1.0);
    let view   = se_look_at(u.eye.xyz, u.focus.xyz, vec3<f32>(0.0, 1.0, 0.0));
    let proj   = se_perspective(u.fov.x, aspect, 0.05, 200.0);
    return proj * view;
}

@vertex
fn vs_main(v : SeVertex, i : SeInstance) -> VsOut {
    // scale, then rotate, then translate — the order `Transform` implies.
    let local = v.pos * i.scale;
    let world = se_qrot(i.rot, local) + i.pos;

    var o : VsOut;
    o.clip   = view_proj() * vec4<f32>(world, 1.0);
    o.normal = normalize(se_qrot(i.rot, v.normal));
    o.world  = world;
    return o;
}
